### ISSUE TITLE
writeStream not working in Glue 4.0 - java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Cast$.apply$default$4()Lscala/Enumeration$Value

### ISSUE THREAD

**Issue by S0nicHedgeH0g** [awslabs/spark-sql-kinesis-connector#15]
Hi, I hope you are doing well. 

I've trying to use this connector with a customer of mine, writing data to kinesis, but when using Glue 4.0 (Spark 3.3.0) we are facing this error:

Error Category: IMPORT_ERROR; StreamingQueryException: Query [id = d926a708-a5c3-491b-8f04-0dbafd10981d, runId = e2fb80f8-7ab0-4530-a81b-5c0de75a6fbe] terminated with exception: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 13) (172.34.80.194 executor 1): java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Cast$.apply$default$4()Lscala/Enumeration$Value;

Looking for the doc we noticed that is mentioned that this version was tested with Spark 3.2 and above (so including the version present in Glue 4.0).

This connector is the only one we are using in our Job, with no other jars included.
Do we have any limitation about using this connector with AWS Glue?

Code I am using:

df = spark \
    .readStream \
    .format("kafka") \
    .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVER) \
    .option("subscribe", TOPIC_NAME) \
    .option("kafka.security.protocol",KAFKA_SECURITY_PROTOCOL) \
    .option("mode", "PERMISSIVE") \
    .option("startingOffset","earliest") \
    .option("kafka.sasl.jaas.config", f'org.apache.kafka.common.security.plain.PlainLoginModule required username="{KAFKA_API_KEY}" password="{KAFKA_API_SECRET}";') \
    .option("kafka.sasl.mechanism", "PLAIN") \
    .load()

grouped_df = df \
                .withWatermark("timestamp", "5 seconds") \
                .groupBy(window("timestamp", "5 seconds"), "address.state") \
                .agg(count("orderid").alias("total_orders")) 

grouped_df = grouped_df.withColumn("window_start_time", col("window.start")) \
                .withColumn("window_end_time", col("window.end")) \
                .drop("window")

df_kinesis = grouped_df.select(f.to_json(f.struct([grouped_df[x] for x in grouped_df.columns])).alias("data"))
df_kinesis = df_kinesis.withColumn("partitionKey", func.expr("uuid()"))

query_1 = df_kinesis \
            .writeStream \
            .format("aws-kinesis") \
            .outputMode("append") \
            .option("kinesis.region", kinesis_region) \
            .option("kinesis.streamName", kinesis_stream_name) \
            .option("kinesis.endpointUrl", kinesis_endpoint) \
            .option("checkpointLocation", checkpoint_writer_kinesis) \
            .trigger(processingTime="5 seconds") \
            .start() \
            .awaitTermination()

**Comment by hwanghw** [comment]
HI S0nicHedgeH0g,   thanks for the details.   

Can you share the full stack trace of the error
```java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Cast$.apply$default$4()Lscala/Enumeration$Value;```
